version: '3.8'

services:
  helpdesk-ratings-dev:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - local
    ports:
      - "50051:50051"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=50051
      - DB_FILE_PATH=/app/database.db
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
    networks:
      - helpdesk-network

  helpdesk-ratings:
    image:
      aiprospace/helpdesk-ratings:v0.2.0
    profiles:
      - remote
    ports:
      - "50051:50051"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=50051
      - DB_FILE_PATH=/app/database.db
    volumes:
      - ./database.db:/app/database.db
    restart: unless-stopped
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    driver: bridge